language: java

jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew clean test --info
deploy:
  provider: script
  script: ./gradlew clean bintrayUpload
  on:
    branch: release