language: java

sudo: false
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew clean test --info
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
deploy:
  provider: script
  script: ./gradlew clean bintrayUpload
  on:
    branch: release