name: Setup Gradle
description: Setup Gradle and JDK
runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: microsoft
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        dependency-graph: generate-and-submit
