name: Deploy

on:
  workflow_dispatch:
    inputs:
      repo:
        type: choice
        description: Publish to which repository
        default: snapshot
        required: true
        options:
          - snapshot
          - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  snapshot:
    if: ${{ github.event.inputs.repo == 'snapshot' }}
    runs-on: macos-latest
    env:
      ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
      ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
      signingKey: ${{ secrets.SIGNING_KEY }}
      signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      versionSuffix: SNAPSHOT
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/setup-gradle

      - name: Publish to snapshot repository
        run: ./gradlew publishAllPublicationsToSnapshotRepository

  staging:
    if: ${{ github.event.inputs.repo == 'staging' }}
    runs-on: macos-latest
    env:
      ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
      ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
      signingKey: ${{ secrets.SIGNING_KEY }}
      signingPassword: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/setup-gradle

      - name: Publish to staging repository
        run: ./gradlew publishAllPublicationsToStagingRepository

  docs:
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/setup-gradle

      - name: Dokka
        run: ./gradlew :dokkaGenerate

      - name: Upload Dokka docs to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/build/dokka/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
